#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal

# Source generated colors.
source "/home/donovan/.cache/wal/colors.sh"

reload_dunst() {
    pkill dunst
    dunst \
        -lb "${color0:-#F0F0F0}" \
        -nb "${color0:-#F0F0F0}" \
        -cb "${color0:-#F0F0F0}" \
        -lf "${color6:=#000000}" \
        -bf "${color6:=#000000}" \
        -cf "${color6:=#000000}" \
        -nf "${color6:=#000000}" \
        -lfr "${color2:=#000000}" \
        -nfr "${color2:=#000000}" \
        #-fn "${DUNST_FONT:-Artwiz Lemon 7}" \
        -geometry "${DUNST_SIZE:-450x30-40+70}" &
}

main() {
    reload_dunst
}

main
